### ISSUE TITLE
How to get a number from the cos() function

### ISSUE THREAD

**Issue by Colt0420** [aunyks/newton-api#11]
How to get a number from cos(23), cos(32), so on an d so forth. 
The cos(pi) works
I tried using pi (over) whatever number, but it returns a string, like cos(1/7 pi).

**Comment by aunyks** [comment]
I know it's been years, but I'm following up on this just in case.  

This API performs most operations symbolically, meaning it will try to return an expression whenever it can instead of a single number. If passing a cosine expression into the `simplify` operation doesn't result in a number, you may need to perform that calculation locally. Most languages' standard libraries include a math package with trigonometric functions.  

If there's something I'm missing, reopen this issue or open another one with more detail. Thanks!
